// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szakgzxhiykbsfztmjeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6YWtnenhoaXlrYnNmenRtamVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjI1ODQsImV4cCI6MjA3MTI5ODU4NH0.jndfLr5ZaQIAVGKlAFGXZfKlvb-tWAPX31FCqDJdrRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});